[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coreinfer"
version = "0.1"
description = "CoreInfer: Accelerating Large Language Model Inference with Semantics-Inspired Adaptive Sparse Activation"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]

dependencies = [
   "torch==2.4.0", "transformers==4.44.2", "accelerate", "safetensors",
   "datasets", "triton", "msgspec", "scipy", "sentence_transformers", "scikit-learn==1.5.1", "lm-eval"
]

[project.optional-dependencies]
eval = ["protobuf","datasets"]


[project.urls]
"Homepage" = "TODO"

[tool.setuptools.packages.find]
exclude = ["notebooks*", "scripts*"]
